name: Build and deploy Node.js app to Azure Web App - node-app-azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Ensure compatibility with Azure App Service

      # Step 3: Increase Node.js memory
      - name: Increase Node.js memory
        run: export NODE_OPTIONS=--max-old-space-size=4096

      # Step 4: Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          npm test --if-present

      # Step 5: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{secrets.AZUREAPPSERVICE_CLIENTID_1EC844949FAC4BE5B9C36C0D7217806E}}
          tenant-id: ${{secrets.AZUREAPPSERVICE_TENANTID_4C13E3BBF1284A3F80C3552E58A03ACA}}
          subscription-id: ${{secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_75B930EB13B3458CAA2881706386751B}}

      # Step 6: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'node-app-azure'
          slot-name: 'Production'
          package: .
