name: Build and deploy Node.js app to Azure Web App - node-app-azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Ensure compatibility with Azure App Service

      # Step 3: Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          npm test --if-present

      # Step 4: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: 'spn' # Service Principal Authentication

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'node-app-azure'
          slot-name: 'Production'
          package: .
