name: Build and deploy Node.js app to Azure Web App - node-app-azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out code from repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies and build the app
      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: |
          npm run build --if-present

      # Test (optional, if you have tests)
      - name: Run tests
        run: |
          npm test --if-present

      # Create ZIP artifact for deployment
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "node_modules/*" "*.git/*" "*.github/*" "*.env" "test/*"

      # Upload the artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip the artifact
      - name: Unzip artifact
        run: unzip release.zip -d app

      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID__3EA656EFF01D43259DC95A2E9AC690F7 }}
          tenant-id: ${{ secrets.AZURE_TENANTID_BC6850FAE69A4DCFBAD76A5865C7F93B }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID_C960913E78A4469F8D48597D0F91714F }}

      # Deploy the app to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'node-app-azure' # Your Azure App Service name
          slot-name: 'Production' # Remove if no slots are used
          package: .
